### ISSUE TITLE
Native mobile text sizes

### ISSUE THREAD

**Issue by RobertJonesFinaps** [mendix/Atlas-theme-default#71]
Hi, while developing a Native app, we have discovered that our text is scaling with the dynamic text. As can be seen in the last image, this makes things unworkable. 

The dynamic text setting can be found:
ios: Settings > General > Accessibility > Larger Text
android: Settings > Display > Font size/ Display size

On smallest setting:
![image](https://user-images.githubusercontent.com/68894338/88637784-e4d6d380-d0ba-11ea-90b1-c4c81a07ca55.png)

On default setting:
![image](https://user-images.githubusercontent.com/68894338/88637872-0041de80-d0bb-11ea-8bf2-cfda4f3a5419.png)

On largest setting:
![image](https://user-images.githubusercontent.com/68894338/88637930-13ed4500-d0bb-11ea-921c-64ed2df0d3ce.png)

Is there a way to prevent or at least constrain this behaviour so that the app can be made more robust to user settings?

**Comment by wegiswes** [comment]
Hi Robert,

This is expected behavior. I don't think you want to prevent/constrain this, as the main reason for the accessibility features is to allow people with disabilities to use your app. So for example, a visually impaired person configured his phone to use a larger font, that all his apps obey to, will find it very hard to use your app when the app has a very small font (compared to the default & other apps).

The only way you can improve the interface a bit is by setting some constrains on the surrounding elements. So for example, setting a fixed `height` or `maxHeight` on a button so only the buttons caption grows, not the button itself. The same goes for input widgets, tabs etc.
Alternatively, if you do want surrounding elements to grow with the text, you should remove all fixed sizing where needed and only work with paddings ;)

**Comment by RobertJonesFinaps** [comment]
Hi Wesley,

That's good to know, thanks!
